### ISSUE TITLE
Softlock at End of Turn

### ISSUE THREAD

**Issue by BP-0321** [ndilday/OnlyWar#10]
Returned to the world of Mass Reorg and it was fine until time came to load the Companies and send them out into the Sector! After assigning the 2nd, 3rd and 4th Companies to their respective Striek Cruisers, setting their course and ending the turn the UI again dissappeared but i was able to Save. Loading the game puts me where it was left but the ships in transit are not visible and the bottom UI disappears at End Turn.

[Player.log](https://github.com/ndilday/OnlyWar/files/7810544/Player.log)

[default.zip](https://github.com/ndilday/OnlyWar/files/7810546/default.zip)

I dont have a real lead on whats causing it right now, gonna start again and see if I can hone in on it!

Update!
I neglected to delete my empty Scout Squads so that feels like a plausable reason. After loading the save and deleting the empty Scout Squads I could once again end the turn fine! However the save button no longer works, and upon exiting the game I can no longer load the game!

I'll try to find more ways to break the save button as it's happened before

**Comment by ndilday** [comment]
Just to check, this is v6.1, yeah?
Interestingly, your log file is still showing the scout-related exception. My current hypothesis is that it's breaking when trying to update the soldiers of a now-empty scout squad, and that's leading to the rest of the turn-end logic not running properly, which led to your fleets ending up in a bad state. (It's possible an unrelated problem broke the fleets, though, as I've definitely had to fix some bad fleet logic in the past.)

Until I get a 0.6.2 out, my recommended workaround is to make sure you delete all empty scout squads before ending the turn; for 0.6.2, I think I'll get rid of the delete button and automatically remove scout squads that you empty out.

**Comment by BP-0321** [comment]
Yup V6.1! If you can play that save file, delete the scouts and progress a turn it breaks the save function.

I'll be suree to delete the empty scouts! Any function you intended to have with keep vacant squads around?

**Comment by ndilday** [comment]
Since I don't currently have a system for creating new squads, and because I'm currently implementing a very Codex-rigid structure, I don't want to allow non-scout squads to be deleted, which is why the delete functionality was only in the recruiting screen. But, as you imply, there's no value right now to keeping empty scout squads around, and since there isn't recruitment of new aspirants yet, no need to create additional squads, so just auto-deleting empty scout squads should be fine as a stopgap.

**Comment by ndilday** [comment]
Yeah, the breakage in that save file is due to the fleets getting messed up, but I can't tell from that save whether the fleets getting messed up was a function of the scout-related mess. :-(

**Comment by BP-0321** [comment]
Okay! I'll try and focus on some fleet shenanigans and see if i can get you something consistent!

**Comment by ndilday** [comment]
Okay, I'll be releasing a new version with the auto-scout-squad-removal before I go to bed, so I'm closing this issue for now.
