### ISSUE TITLE
Failure to Load after Reorganization (no scout changes)

### ISSUE THREAD

**Issue by EuchreJack** [ndilday/OnlyWar#14]
Ended turn approximately 22 times, then reorganized.
Promoted Assaults to Tacticals, moved some Assaults into other company's Assault squad, same with Devastator.
[default.zip](https://github.com/ndilday/OnlyWar/files/7812570/default.zip)
[Player.log](https://github.com/ndilday/OnlyWar/files/7812575/Player.log)
[Player-prev.log](https://github.com/ndilday/OnlyWar/files/7812576/Player-prev.log)

**Comment by ndilday** [comment]
These logs are basically dupes of #13
