### ISSUE TITLE
Battle freezes up

### ISSUE THREAD

**Issue by EuchreJack** [ndilday/OnlyWar#15]
Battle successfully engages, but a couple of turns into the battle, the next phase button disappears.
[default.zip](https://github.com/ndilday/OnlyWar/files/7813042/default.zip)
[Player.log](https://github.com/ndilday/OnlyWar/files/7813067/Player.log)
[Player-prev.log](https://github.com/ndilday/OnlyWar/files/7813068/Player-prev.log)

**Comment by ndilday** [comment]
Whoops. Fixed in https://github.com/ndilday/OnlyWar/commit/6655ff65b262da8a3f3683d23678708d6749ee41
