### ISSUE TITLE
Apothecarium Screen - Incorrect Elements Displayed

### ISSUE THREAD

**Issue by BP-0321** [ndilday/OnlyWar#7]
On the Apothecarium Screen the wrong elements are displayed when selecting Companies

When selecting "First Company" it displays the Armory personnel, and the Company Command squad  is not listed in the drop down. Same for the "Second Company" displaying the Librarius personnel, "Third Company" displaying Apothecarion, and "Fourth Company" displaying Reclusium.

"Fifth-Tenth" Companies display nothing

**Comment by ndilday** [comment]
Fixed in https://github.com/ndilday/OnlyWar/commit/b56bf8a0ca03e44c973ee91a45c0151628ae462a
