### ISSUE TITLE
Freezeup at end turn

### ISSUE THREAD

**Issue by BP-0321** [ndilday/OnlyWar#9]
After considerable Chapter Reorg, ending the turn leaves the game in a soft lock kind of state. The date changes and turn moves to the next, but the bottom hud disappears and cannot be interacted with. I can however click on and interact with planets and fleets.

This only seems to happen after a substantial amount of reassignments on the first turn. This includes filling the 2nd, 3rd, 8th and 9th Companies to full strength. I'm going to try to the same level of reorg but on the second turn, and then doing it one company at a time, or then by squad per turn etc

[Player.log](https://github.com/ndilday/OnlyWar/files/7801655/Player.log)
[Player-prev.log](https://github.com/ndilday/OnlyWar/files/7801656/Player-prev.log)

[default.zip](https://github.com/ndilday/OnlyWar/files/7801676/default.zip)

Having trouble linking the save, let me know if this works.

**Comment by EuchreJack** [comment]
Same
[Player.log](https://github.com/ndilday/OnlyWar/files/7805473/Player.log)
[default.zip](https://github.com/ndilday/OnlyWar/files/7805482/default.zip)

**Comment by ndilday** [comment]
These look like they were both also due to the deleted scout squad problems fixed inhttps://github.com/ndilday/OnlyWar/commit/6bfbbf9e2125e89815a9d6d711c3e3db09d4d1a7 , so I'm closing this issue for now, but I won't be surprised if there are other massive-reorg related bugs you'll find.
